import fs from 'fs/promises';
import path from 'path';
import type { HookEventType } from '../../shared/types.js';

interface HookEntry {
  type: 'command';
  powershell: string;
  cwd: string;
  timeoutSec: number;
}

interface HooksConfig {
  version: number;
  hooks: Record<string, HookEntry[]>;
}

const HOOK_TYPES: { eventType: HookEventType; scriptName: string }[] = [
  { eventType: 'sessionStart', scriptName: 'session-start.ps1' },
  { eventType: 'sessionEnd', scriptName: 'session-end.ps1' },
  { eventType: 'userPromptSubmitted', scriptName: 'prompt-submitted.ps1' },
  { eventType: 'preToolUse', scriptName: 'pre-tool-use.ps1' },
  { eventType: 'postToolUse', scriptName: 'post-tool-use.ps1' },
  { eventType: 'errorOccurred', scriptName: 'error-occurred.ps1' },
];

function generateScript(eventType: HookEventType, serverUrl: string, projectPath: string): string {
  const escapedPath = projectPath.replace(/\\/g, '\\\\');
  return `# Auto-generated by squadCenter — ${eventType} hook
try {
    $inputJson = [Console]::In.ReadToEnd()
    $inputData = $inputJson | ConvertFrom-Json

    $body = @{
        eventType   = "${eventType}"
        projectPath = "${escapedPath}"
        data        = $inputData
    } | ConvertTo-Json -Depth 10 -Compress

    Invoke-RestMethod -Uri "${serverUrl}/api/hooks/event" \`
        -Method Post \`
        -ContentType "application/json" \`
        -Body $body \`
        -TimeoutSec 5 | Out-Null
} catch {
    # Silently fail — hooks must not block the CLI
}
`;
}

export async function generateHooksConfig(
  projectPath: string,
  serverUrl = 'http://localhost:3001',
): Promise<string> {
  const hooksDir = path.join(projectPath, '.github', 'hooks');
  await fs.mkdir(hooksDir, { recursive: true });

  const config: HooksConfig = {
    version: 1,
    hooks: {},
  };

  for (const { eventType, scriptName } of HOOK_TYPES) {
    const scriptContent = generateScript(eventType, serverUrl, projectPath);
    await fs.writeFile(path.join(hooksDir, scriptName), scriptContent, 'utf-8');

    config.hooks[eventType] = [
      {
        type: 'command',
        powershell: `./.github/hooks/${scriptName}`,
        cwd: '.',
        timeoutSec: 10,
      },
    ];
  }

  const hooksJsonPath = path.join(hooksDir, 'hooks.json');
  await fs.writeFile(hooksJsonPath, JSON.stringify(config, null, 2), 'utf-8');

  return hooksDir;
}
